compressionLevel: mixed

enableGlobalCache: true

logFilters:
  - level: discard
    pattern: provides react * with version 18
  - level: discard
    pattern: provides react-dom * with version 18
  - level: discard
    pattern: provides @types/react * with version 18
  - level: discard
    pattern: "@types/jest * with version 29.1.2"

packageExtensions:
  "@codemirror/lang-html@*":
    peerDependencies:
      "@codemirror/view": "*"
  "@docsearch/react@*":
    peerDependencies:
      "@algolia/client-search": ^4.9.1
  "@docusaurus/theme-search-algolia@*":
    dependencies:
      "@algolia/client-search": ^4.9.1
      prism-react-renderer: ^1.2.1
  "@lezer/css@*":
    dependencies:
      "@lezer/common": 0.15.12
  "@lezer/html@*":
    dependencies:
      "@lezer/common": 0.15.12
  "@lezer/javascript@*":
    dependencies:
      "@lezer/common": 0.15.12
  "@octokit/rest@^16":
    dependencies:
      "@octokit/core": ^3.0.0
  "@svgr/core@*":
    peerDependencies:
      "@babel/core": "*"
  chalk@*:
    dependencies:
      "#ansi-styles": "npm:ansi-styles@6.1.0"
      "#supports-color": "npm:supports-color@9.2.2"
  react-devtools-inline@4.4.0:
    dependencies:
      scheduler: 0.23.0
    peerDependencies:
      react-is: "*"

plugins:
  - checksum: b1c1ddcd967b168da2e329ce1fe95ede85b1327032e5fa8725516df4e72a1cddb6c608925def5f1fc7dd64742d1c64cf125bc10753e4f8956872128a4a2d750a
    path: .yarn/plugins/@yarnpkg/plugin-workspace-since.cjs
    spec: "https://raw.githubusercontent.com/toss/yarn-plugin-workspace-since/main/bundles/%40yarnpkg/plugin-workspace-since.js"

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-4.1.1.cjs
