/* eslint-disable @typescript-eslint/no-var-requires */
module.exports.rules = {
  'ban-characters': require('./rules/ban-characters'),
  'ban-http-link': require('./rules/ban-http-link'),
  'ban-toss-github-io': require('./rules/ban-toss-github-io'),
  'ban-app-bridge-post-message': require('./rules/ban-app-bridge-post-message'),
  'ban-get-initial-props': require('./rules/ban-get-initial-props'),
  'meta-props': require('./rules/meta-props'),
  'exhaustive-deps': require('./rules/exhaustive-deps'),
  'ban-lodash': require('./rules/ban-lodash'),
  'ban-direct-motion-component': require('./rules/ban-direct-motion-component'),
  'ban-useless-catch': require('./rules/ban-useless-catch/ban-useless-catch'),
  'ban-sentry-only-catch/react': require('./rules/ban-useless-catch/ban-sentry-only-catch').insideComponent,
  'ban-sentry-only-catch/common': require('./rules/ban-useless-catch/ban-sentry-only-catch').outsideComponent,
  'ban-ssr-unsafe-method': require('./rules/ban-ssr-unsafe-method'),
  'safely-navigate-to': require('./rules/safely-navigate-to'),
  'rules-of-hooks': require('./rules/rules-of-hooks'),
  'ban-use-query-param-boolean': require('./rules/ban-use-query-param-boolean'),
  'ban-axios': require('./rules/ban-axios'),
};
